# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class User(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, id: str=None, score: float=None):  # noqa: E501
        """User - a model defined in Swagger

        :param name: The name of this User.  # noqa: E501
        :type name: str
        :param id: The id of this User.  # noqa: E501
        :type id: str
        :param score: The score of this User.  # noqa: E501
        :type score: float
        """
        self.swagger_types = {
            'name': str,
            'id': str,
            'score': float
        }

        self.attribute_map = {
            'name': 'name',
            'id': 'id',
            'score': 'score'
        }

        self._name = name
        self._id = id
        self._score = score

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this User.

        User name  # noqa: E501

        :return: The name of this User.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this User.

        User name  # noqa: E501

        :param name: The name of this User.
        :type name: str
        """

        self._name = name

    @property
    def id(self) -> str:
        """Gets the id of this User.

        User ID  # noqa: E501

        :return: The id of this User.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this User.

        User ID  # noqa: E501

        :param id: The id of this User.
        :type id: str
        """

        self._id = id

    @property
    def score(self) -> float:
        """Gets the score of this User.

        User balance  # noqa: E501

        :return: The score of this User.
        :rtype: float
        """
        return self._score

    @score.setter
    def score(self, score: float):
        """Sets the score of this User.

        User balance  # noqa: E501

        :param score: The score of this User.
        :type score: float
        """

        self._score = score
